version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "50444:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs_app
    networks:
      - app-network

  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge